### ISSUE TITLE
Error TypeError: secret must be a string or buffer

### ISSUE THREAD

**Issue by ysilvela** [huseyinbabal/token-based-auth-backend#4]
/var/lib/openshift/557e86cd5004461739000119/app-root/runtime/repo/node_modules/mongoose/lib/utils.js:413
        throw err;
              ^
TypeError: secret must be a string or buffer
    at typeError (/var/lib/openshift/557e86cd5004461739000119/app-root/runtime/repo/node_modules/jsonwebtoken/node_modules/jws/node_modules/jwa/index
js:12:10)
    at Object.sign (/var/lib/openshift/557e86cd5004461739000119/app-root/runtime/repo/node_modules/jsonwebtoken/node_modules/jws/node_modules/jwa/ind
x.js:28:13)
    at Object.jwsSign [as sign](/var/lib/openshift/557e86cd5004461739000119/app-root/runtime/repo/node_modules/jsonwebtoken/node_modules/jws/index.j
:34:26)
    at Object.module.exports.sign (/var/lib/openshift/557e86cd5004461739000119/app-root/runtime/repo/node_modules/jsonwebtoken/index.js:28:20)
    at Promise.<anonymous> (/var/lib/openshift/557e86cd5004461739000119/app-root/runtime/repo/api/routes.js:74:24)
    at Promise.<anonymous> (/var/lib/openshift/557e86cd5004461739000119/app-root/runtime/repo/node_modules/mongoose/node_modules/mpromise/lib/promise
js:177:8)
    at Promise.EventEmitter.emit (events.js:98:17)
    at Promise.emit (/var/lib/openshift/557e86cd5004461739000119/app-root/runtime/repo/node_modules/mongoose/node_modules/mpromise/lib/promise.js:84:
8)
    at Promise.fulfill (/var/lib/openshift/557e86cd5004461739000119/app-root/runtime/repo/node_modules/mongoose/node_modules/mpromise/lib/promise.js:
7:20)
    at handleSave (/var/lib/openshift/557e86cd5004461739000119/app-root/runtime/repo/node_modules/mongoose/lib/model.js:133:13)

**Comment by huseyinbabal** [comment]
Have you set environment variable JWT_SECRET ? This secret password is used to sign your data .

**Comment by huseyinbabal** [comment]
JWT requires a secret to sign your data, it will work fine when you set environment variable JWT_SECRET=your secret

**Comment by ratnesh2581990** [comment]
Where do i get this JWT_SECRET can you guide me on this

**Comment by prerna-bhatra** [comment]
i tried evrthing nothing works
